### ISSUE TITLE
SSpanel前后端分离，落地机上报错

### ISSUE THREAD

**Issue by ZJahon** [XrayR-project/XrayR-release#12]
Mar 20 22:46:32 vultr.guest systemd[1]: XrayR.service holdoff time over, scheduling restart.
Mar 20 22:46:32 vultr.guest systemd[1]: Stopped XrayR Service.
Mar 20 22:46:32 vultr.guest systemd[1]: Started XrayR Service.
Mar 20 22:46:32 vultr.guest XrayR[10270]: XrayR 0.7.6 (A Xray backend that supports many panels)
Mar 20 22:46:32 vultr.guest XrayR[10270]: 2022/03/20 22:46:32 Start the panel..
Mar 20 22:46:32 vultr.guest XrayR[10270]: 2022/03/20 22:46:32 Xray Core Version: 1.5.2
Mar 20 22:46:32 vultr.guest XrayR[10270]: 2022/03/20 22:46:32 Panel Start fialed: Ret {"ret":0,"data":"token or source is invalid, Your ip address is 12.12.100.254"} invalid
Mar 20 22:46:32 vultr.guest XrayR[10270]: panic: Panel Start fialed: Ret {"ret":0,"data":"token or source is invalid, Your ip address is 12.12.100.254"} invalid
Mar 20 22:46:32 vultr.guest XrayR[10270]: goroutine 1 [running]:
Mar 20 22:46:32 vultr.guest XrayR[10270]: log.Panicf({0x208d5e6, 0x0}, {0xc0007d1ea0, 0xc000521030, 0xc0005bfe88})
Mar 20 22:46:32 vultr.guest XrayR[10270]: log/log.go:361 +0x67
Mar 20 22:46:32 vultr.guest XrayR[10270]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc000522100)
Mar 20 22:46:32 vultr.guest XrayR[10270]: github.com/XrayR-project/XrayR/panel/panel.go:194 +0x588
Mar 20 22:46:32 vultr.guest XrayR[10270]: main.main()
Mar 20 22:46:32 vultr.guest XrayR[10270]: github.com/XrayR-project/XrayR/main/main.go:92 +0x1ed
Mar 20 22:46:32 vultr.guest systemd[1]: XrayR.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 20 22:46:32 vultr.guest systemd[1]: Unit XrayR.service entered failed state.
Mar 20 22:46:32 vultr.guest systemd[1]: XrayR.service failed.

**Comment by ZJahon** [comment]
前端部署在自己的主机上，通过路由器连接着外网，有公网ip，里面的12.12.100.254就是路由器网关
