### ISSUE TITLE
对接sspanel的shadowsocks2022提示missing key

### ISSUE THREAD

**Issue by x-liao** [XrayR-project/XrayR-release#16]
Custom_config
```
{
    "offset_port_node": "8080",
    "method": "2022-blake3-aes-128-gcm",
    "server_key": "zP6flOl9PSsHr019zGSV6Q=="
}

```

xrayr log
```
Dec 16 11:57:38 smoke systemd[1]: Stopped XrayR.service - XrayR Service.
Dec 16 11:57:38 smoke systemd[1]: Started XrayR.service - XrayR Service.
Dec 16 11:57:38 smoke XrayR[158609]: XrayR 0.9.1 (A Xray backend that supports many panels)
Dec 16 11:57:38 smoke XrayR[158609]: 2023/12/16 11:57:38 Start the panel..
Dec 16 11:57:38 smoke XrayR[158609]: 2023/12/16 11:57:38 Xray Core Version: 1.8.4
Dec 16 11:57:38 smoke XrayR[158609]: 2023/12/16 11:57:38 [Debug] app/log: Logger started
Dec 16 11:57:38 smoke XrayR[158609]: 2023/12/16 11:57:38 [Info] app/dns: DNS: created localhost client
Dec 16 11:57:38 smoke XrayR[158609]: 2023/12/16 11:57:38 [Warning] core: Xray 1.8.4 started
Dec 16 11:57:38 smoke XrayR[158609]: 2023/12/16 11:57:38 proxy/shadowsocks_2022: missing key
Dec 16 11:57:38 smoke XrayR[158609]: panic: proxy/shadowsocks_2022: missing key
Dec 16 11:57:38 smoke XrayR[158609]: goroutine 1 [running]:
Dec 16 11:57:38 smoke XrayR[158609]: log.Panic({0xc0008b7c68?, 0xc0006da100?, 0xc0008b7ce8?})
Dec 16 11:57:38 smoke XrayR[158609]:         log/log.go:432 +0x5a
Dec 16 11:57:38 smoke XrayR[158609]: github.com/XrayR-project/XrayR/service/controller.(*Controller).Start(0xc0006da700)
Dec 16 11:57:38 smoke XrayR[158609]:         github.com/XrayR-project/XrayR/service/controller/controller.go:88 +0x26f
Dec 16 11:57:38 smoke XrayR[158609]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc00052b400)
Dec 16 11:57:38 smoke XrayR[158609]:         github.com/XrayR-project/XrayR/panel/panel.go:208 +0x596
Dec 16 11:57:38 smoke XrayR[158609]: main.main()
Dec 16 11:57:38 smoke XrayR[158609]:         github.com/XrayR-project/XrayR/main/main.go:97 +0x233
Dec 16 11:57:38 smoke systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 16 11:57:38 smoke systemd[1]: XrayR.service: Failed with result 'exit-code'.
```

**Comment by arsenelupin729** [comment]
我也遇到此问题，版本0.9.1，降本到0.8.9就没问题，目前还没找到解决方案。
