### ISSUE TITLE
docker compose安装运行出现问题

### ISSUE THREAD

**Issue by RookieTerry** [XrayR-project/XrayR-release#23]
如题，报错信息可能与内核有关，Linux发行版是Debian 10：
```
XrayR 0.9.4 (A Xray backend that supports many panels)
time="2024-12-16T08:53:11+08:00" level=info msg="Start the panel.."
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x33455b9]

goroutine 1 [running]:
github.com/XrayR-project/XrayR/service/controller.InboundBuilder(0xc0018d98c0, 0xc0018e5200, {0xc0011d1938, 0x13})
        github.com/XrayR-project/XrayR/service/controller/inboundbuilder.go:248 +0x15f9
github.com/XrayR-project/XrayR/service/controller.(*Controller).addNewTag(0xc0018c30e0, 0xc0018e5200)
        github.com/XrayR-project/XrayR/service/controller/controller.go:327 +0x75
github.com/XrayR-project/XrayR/service/controller.(*Controller).Start(0xc0018c30e0)
        github.com/XrayR-project/XrayR/service/controller/controller.go:93 +0x225
github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc0018776c0)
        github.com/XrayR-project/XrayR/panel/panel.go:209 +0x5ca
github.com/XrayR-project/XrayR/cmd.run()
        github.com/XrayR-project/XrayR/cmd/root.go:106 +0x1c5
github.com/XrayR-project/XrayR/cmd.init.func1(0xc0018aa400?, {0x445285b?, 0x4?, 0x445274b?})
        github.com/XrayR-project/XrayR/cmd/root.go:27 +0x13
github.com/spf13/cobra.(*Command).execute(0x780b740, {0xc000072970, 0x2, 0x2})
        github.com/spf13/cobra@v1.8.0/command.go:987 +0xab1
github.com/spf13/cobra.(*Command).ExecuteC(0x780b740)
        github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/XrayR-project/XrayR/cmd.Execute(...)
        github.com/XrayR-project/XrayR/cmd/root.go:120
main.main()
        github.com/XrayR-project/XrayR/main.go:10 +0x1a
```

**Comment by zach-jin** [comment]
跟你出现一样的报错
